// This file was generated by Prisma. Loading dotenv is optional in runtime.
// Try to require dotenv only if it's available to avoid runtime errors in containers.
try {
  require('dotenv/config');
} catch (e) {
  // dotenv not installed in this environment — proceed without it
}
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
});
